### ISSUE TITLE
wryyy

### ISSUE THREAD

**Issue by ArjixWasTaken** [AutumnVN/highlight#1]
Great idea, now use [shiki](https://github.com/shikijs/shiki).

![a](https://media.discordapp.net/stickers/1039992459209490513.png)

**Comment by ArjixWasTaken** [comment]
(if you are open to PRs, then I will do it myself)

**Comment by AutumnVN** [comment]
i have tried shiki initially, 
it works on files from my website but raw files from github give `compile error webassembly.instantiatestreaming()`
and i have no idea what wrong :(

btw prs are welcome :D 

edit: added back shiki in `shiki` branch
that problem seems only happen on raw.githubusercontent.com, it works on most other place

**Comment by AutumnVN** [comment]
oh it is because of csp

**Comment by AutumnVN** [comment]
made it worked with manifest v2
shiki is now on main branch
